GET http://localhost:3001/api/ping

################################################################################

GET http://localhost:3001/api/diagnoses

################################################################################

POST http://localhost:3001/api/diagnoses
Content-Type: application/json

{
  "code" : "A000",
  "name" : "Acute Bronchitis",
  "latin" : "Acute Bronchitis"
}

################################################################################
GET http://localhost:3001/api/patients

################################################################################

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

################################################################################

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
################################################################################

POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

  {
    "type": "OccupationalHealthcare",
    "employerName": "Hospital A",
    "date": "2019-12-01",
    "description": "Patient is complaining about pain in the chest",
    "specialist": "MD House",
    "diagnosisCodes": ["A000", "A001"]
  }
################################################################################

POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "ssn": "123-45-6789",
  "dateOfBirth": "1980-01-01",
  "gender" : "male",
  "occupation": "detective"
}
