###

 GET  http://localhost:3003/api/blogs/
###
 GET http://localhost:3003/api/users 
###
DELETE http://localhost:3003/api/blogs/616c604df39fd5b40c317514
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlbW8xMTIzNSIsImlkIjoiNjE2YzNlOTZjODgxYTg5NDhkMTMyZWYxIiwiaWF0IjoxNjM0NDg0OTI5fQ.3bZtMvAmZGGJcdnqUIRREssZ4nS87Vo9-N4ENu7my6g 

###
POST http://localhost:3003/api/blogs/ 
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlbW8xMTIzNSIsImlkIjoiNjE2YzNlOTZjODgxYTg5NDhkMTMyZWYxIiwiaWF0IjoxNjM0NDg0OTI5fQ.3bZtMvAmZGGJcdnqUIRREssZ4nS87Vo9-N4ENu7my6g 

{
    "title": "My token test blog fourth",
    "author": "Me and myself",
    "likes": 5,
    "url": "www.tokentest.com"
}
###
POST http://localhost:3003/api/users/ 
Content-Type: application/json

{
    "username": "Pemo11235",
    "name": "Pemo11235",
    "password": "Pemo11235"
}
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"Pemo11235",
    "password": "Pemo11235"
}